[package]
name = "rusted-armor"
version = "0.1.0"
authors = ["Anwar Ludin <anwar.ludin@algonents.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
