[package]
name = "armored_api"
version = "0.1.0"
authors = ["Anwar Ludin <anwar.ludin@algonents.com>"]
edition = "2018"

[dependencies]

serde = "1.0.105"
serde_derive = "1.0.105"
serde_json = "1.0.48"

hyper = "0.13"
tokio = { version = "0.2", features = ["full"] }
